/**
 * Alert Generation Service
 * Generates real-time system alerts based on actual platform metrics
 */

import { createClient } from '@/lib/supabase/server';

interface AlertParams {
  name: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  type: 'system' | 'security' | 'performance' | 'cost' | 'database' | 'api';
  affectedResources?: string[];
  metadata?: Record<string, any>;
}

/**
 * Create a system alert
 */
async function createSystemAlert(params: AlertParams): Promise<void> {
  const supabase = await createClient();

  // Insert alert
  const { data: alert, error: insertError } = await supabase
    .from('system_alerts')
    .insert({
      name: params.name,
      description: params.description,
      severity: params.severity,
      type: params.type,
      status: 'active',
      triggered_at: new Date().toISOString(),
      affected_resources: params.affectedResources || [],
      metadata: params.metadata || {},
    })
    .select()
    .single();

  if (insertError) {
    console.error('Error creating system alert:', insertError);
    return;
  }

  // Create timeline entry
  await supabase.from('alert_timeline').insert({
    alert_id: alert.id,
    action: 'created',
    actor_name: 'System',
    timestamp: new Date().toISOString(),
    notes: 'Alert generated by automated monitoring system',
  });
}

/**
 * Generate cost-related alerts based on API usage
 */
export async function generateCostAlerts(): Promise<number> {
  const supabase = await createClient();
  let alertsCreated = 0;

  try {
    // Check if api_cost_tracking table exists
    const { data: costData, error: costError } = await supabase
      .from('api_cost_tracking')
      .select('user_id, cost_cents, created_at')
      .gte('created_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());

    if (costError || !costData) {
      console.log('No cost tracking data available');
      return 0;
    }

    // Aggregate costs by user for last 24 hours
    const userCosts = costData.reduce(
      (acc, record) => {
        if (!acc[record.user_id]) {
          acc[record.user_id] = 0;
        }
        acc[record.user_id] += record.cost_cents;
        return acc;
      },
      {} as Record<string, number>
    );

    // Create alerts for high daily costs
    for (const [userId, totalCents] of Object.entries(userCosts)) {
      // Critical: > $10/day
      if (totalCents > 1000) {
        // Check if alert already exists for this user today
        const { data: existing } = await supabase
          .from('system_alerts')
          .select('id')
          .eq('type', 'cost')
          .eq('status', 'active')
          .contains('affected_resources', [userId])
          .gte('triggered_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString())
          .single();

        if (!existing) {
          await createSystemAlert({
            name: 'High Daily API Cost',
            description: `API costs for user ${userId} have exceeded $${(totalCents / 100).toFixed(2)} in the last 24 hours. This is significantly higher than expected and requires immediate investigation.`,
            severity: totalCents > 2000 ? 'critical' : 'high',
            type: 'cost',
            affectedResources: [userId],
            metadata: {
              cost_cents: totalCents,
              cost_usd: (totalCents / 100).toFixed(2),
              period: '24h',
              threshold_cents: 1000,
            },
          });
          alertsCreated++;
        }
      }
    }

    // Check monthly costs
    const { data: monthlyData } = await supabase
      .from('api_cost_tracking')
      .select('user_id, cost_cents')
      .gte(
        'created_at',
        new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString()
      );

    if (monthlyData) {
      const monthlyUserCosts = monthlyData.reduce(
        (acc, record) => {
          if (!acc[record.user_id]) {
            acc[record.user_id] = 0;
          }
          acc[record.user_id] += record.cost_cents;
          return acc;
        },
        {} as Record<string, number>
      );

      // Alert for users approaching $50/month
      for (const [userId, totalCents] of Object.entries(monthlyUserCosts)) {
        if (totalCents > 4000) {
          // > $40
          const { data: existing } = await supabase
            .from('system_alerts')
            .select('id')
            .eq('type', 'cost')
            .eq('status', 'active')
            .contains('metadata', { period: 'monthly' })
            .contains('affected_resources', [userId])
            .gte('triggered_at', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString())
            .single();

          if (!existing) {
            await createSystemAlert({
              name: 'Monthly Cost Budget Alert',
              description: `User ${userId} has spent $${(totalCents / 100).toFixed(2)} this month, approaching the $50 monthly threshold. Monitor usage to prevent overages.`,
              severity: 'medium',
              type: 'cost',
              affectedResources: [userId],
              metadata: {
                cost_cents: totalCents,
                cost_usd: (totalCents / 100).toFixed(2),
                period: 'monthly',
                threshold_cents: 5000,
                percentage: ((totalCents / 5000) * 100).toFixed(1),
              },
            });
            alertsCreated++;
          }
        }
      }
    }
  } catch (error) {
    console.error('Error generating cost alerts:', error);
  }

  return alertsCreated;
}

/**
 * Generate database-related alerts
 */
export async function generateDatabaseAlerts(): Promise<number> {
  const supabase = await createClient();
  let alertsCreated = 0;

  try {
    // Check for large tables (this is a placeholder - adjust based on your needs)
    const { data: blueprints, error } = await supabase
      .from('blueprint_generator')
      .select('id', { count: 'exact', head: true });

    if (!error && blueprints !== null) {
      const count = blueprints;

      // Alert if blueprint table is growing large
      if (count > 10000) {
        const { data: existing } = await supabase
          .from('system_alerts')
          .select('id')
          .eq('type', 'database')
          .eq('status', 'active')
          .ilike('name', '%Blueprint Table Growth%')
          .gte('triggered_at', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString())
          .single();

        if (!existing) {
          await createSystemAlert({
            name: 'Blueprint Table Growth Alert',
            description: `The blueprint_generator table has reached ${count.toLocaleString()} records. Consider implementing archival policies or cleanup strategies.`,
            severity: count > 50000 ? 'high' : 'medium',
            type: 'database',
            affectedResources: ['blueprint_generator'],
            metadata: {
              table_name: 'blueprint_generator',
              record_count: count,
              threshold: 10000,
            },
          });
          alertsCreated++;
        }
      }
    }
  } catch (error) {
    console.error('Error generating database alerts:', error);
  }

  return alertsCreated;
}

/**
 * Generate system health alerts
 */
export async function generateSystemAlerts(): Promise<number> {
  const supabase = await createClient();
  let alertsCreated = 0;

  try {
    // Check for users with many failed blueprint generations
    const { data: failedBlueprints } = await supabase
      .from('blueprint_generator')
      .select('user_id')
      .eq('status', 'error')
      .gte('created_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());

    if (failedBlueprints && failedBlueprints.length > 10) {
      const { data: existing } = await supabase
        .from('system_alerts')
        .select('id')
        .eq('type', 'system')
        .eq('status', 'active')
        .ilike('name', '%Blueprint Generation Failures%')
        .gte('triggered_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString())
        .single();

      if (!existing) {
        await createSystemAlert({
          name: 'High Blueprint Generation Failure Rate',
          description: `${failedBlueprints.length} blueprint generation failures detected in the last 24 hours. This may indicate an issue with the AI service or validation logic.`,
          severity: failedBlueprints.length > 50 ? 'critical' : 'high',
          type: 'system',
          affectedResources: ['blueprint_service'],
          metadata: {
            failure_count: failedBlueprints.length,
            period: '24h',
            threshold: 10,
          },
        });
        alertsCreated++;
      }
    }

    // Check for inactive users (potential churn)
    const { data: totalUsers } = await supabase
      .from('user_profiles')
      .select('user_id', { count: 'exact', head: true });

    const { data: activeUsers } = await supabase
      .from('blueprint_generator')
      .select('user_id')
      .gte('created_at', new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString());

    if (totalUsers && activeUsers) {
      const activeCount = new Set(activeUsers.map((u) => u.user_id)).size;
      const inactiveCount = totalUsers - activeCount;
      const inactivePercentage = (inactiveCount / totalUsers) * 100;

      if (inactivePercentage > 50) {
        const { data: existing } = await supabase
          .from('system_alerts')
          .select('id')
          .eq('type', 'system')
          .eq('status', 'active')
          .ilike('name', '%User Inactivity%')
          .gte('triggered_at', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString())
          .single();

        if (!existing) {
          await createSystemAlert({
            name: 'High User Inactivity Rate',
            description: `${inactivePercentage.toFixed(1)}% of users (${inactiveCount} out of ${totalUsers}) have been inactive for 30+ days. Consider engagement campaigns or feature improvements.`,
            severity: 'medium',
            type: 'system',
            metadata: {
              inactive_count: inactiveCount,
              total_users: totalUsers,
              percentage: inactivePercentage.toFixed(1),
              period: '30d',
            },
          });
          alertsCreated++;
        }
      }
    }
  } catch (error) {
    console.error('Error generating system alerts:', error);
  }

  return alertsCreated;
}

/**
 * Generate all alerts - main entry point
 */
export async function generateAllAlerts(): Promise<{
  total: number;
  byType: Record<string, number>;
}> {
  console.log('[Alert Generation] Starting alert generation...');

  const costAlerts = await generateCostAlerts();
  const databaseAlerts = await generateDatabaseAlerts();
  const systemAlerts = await generateSystemAlerts();

  const total = costAlerts + databaseAlerts + systemAlerts;

  console.log(`[Alert Generation] Created ${total} new alerts`);
  console.log(`  - Cost alerts: ${costAlerts}`);
  console.log(`  - Database alerts: ${databaseAlerts}`);
  console.log(`  - System alerts: ${systemAlerts}`);

  return {
    total,
    byType: {
      cost: costAlerts,
      database: databaseAlerts,
      system: systemAlerts,
    },
  };
}
