import React from 'react';
import { Sparkles, Award, BookOpen, Users2, TrendingUp, Presentation } from 'lucide-react';
import type { PersonaData } from './types';

export const personasData: PersonaData[] = [
  {
    id: 'instructional-designer',
    icon: <Sparkles className="h-5 w-5" strokeWidth={2} />,
    label: 'ID',
    title: 'Instructional Designer',
    subtitle: 'Transform Course Design from Weeks to Hours',
    benefits: [
      'AI-assisted curriculum mapping in 20 minutes',
      "Automated learning objective generation (Bloom's aligned)",
      'ADDIE-aligned design structure',
      'Assessment strategy automation (formative + summative)',
      'Scaffolding and prerequisite recommendations',
      'Universal Design for Learning (UDL) alignment',
      'Export to PDF, Markdown, or JSON for your workflow',
    ],
    stats: [
      { value: 85, suffix: '%', label: 'Faster Design' },
      { value: 12, suffix: ' hrs', label: 'Avg Time Saved' },
    ],
    color: '#a7dadb',
    gradient: 'from-[#a7dadb] to-[#7bc5c7]',
  },
  {
    id: 'lxd-specialist',
    icon: <Award className="h-5 w-5" strokeWidth={2} />,
    label: 'LXD',
    title: 'Learning Experience Designer',
    subtitle: 'Craft Experiences That Transform',
    benefits: [
      'Audience segmentation and persona mapping',
      'Engagement strategy recommendations',
      'Success metrics and KPI definition',
      'Technology stack integration planning',
      'Iterative refinement with visual JSON editor',
      'Collaboration tools for stakeholder reviews',
      'Multi-modal learning path design',
    ],
    stats: [
      { value: 65, suffix: '%', label: 'Time Reduction' },
      { value: 70, suffix: '+', label: 'Adaptive Questions' },
    ],
    color: '#4f46e5',
    gradient: 'from-[#4f46e5] to-[#7c69f5]',
  },
  {
    id: 'training-facilitator',
    icon: <Presentation className="h-5 w-5" strokeWidth={2} />,
    label: 'Facilitator',
    title: 'Training Facilitator',
    subtitle: 'Deliver Impactful Sessions with Ready-to-Use Designs',
    benefits: [
      'Pre-built session plans with timing and activities',
      'Facilitation guides with talking points and transitions',
      'Interactive exercise recommendations aligned to objectives',
      'Assessment tools for measuring participant progress',
      'Adaptable content for virtual, hybrid, and in-person formats',
      'Resource lists and handout templates',
      'Engagement strategies for diverse learning styles',
    ],
    stats: [
      { value: 75, suffix: '%', label: 'Prep Time Saved' },
      { value: 90, suffix: '+', label: 'Session Activities' },
    ],
    color: '#a7dadb',
    gradient: 'from-[#a7dadb] to-[#7bc5c7]',
  },
  {
    id: 'content-developer',
    icon: <BookOpen className="h-5 w-5" strokeWidth={2} />,
    label: 'CD',
    title: 'Content Developer',
    subtitle: 'From Concept to Content Architecture in Under an Hour',
    benefits: [
      'Detailed module breakdowns with learning paths',
      'Content type recommendations (video, interactive, text)',
      'Resource lists aligned to learning objectives',
      'Assessment design with question bank guidance',
      'Markdown export for CMS integration',
      'Batch design generation for multiple courses',
      'Version control and change tracking',
    ],
    stats: [
      { value: 45, suffix: ' min', label: 'Avg Design Time' },
      { value: 3, suffix: '+', label: 'Export Formats' },
    ],
    color: '#10b981',
    gradient: 'from-[#10b981] to-[#34d399]',
  },
  {
    id: 'id-manager',
    icon: <Users2 className="h-5 w-5" strokeWidth={2} />,
    label: 'Manager',
    title: 'L&D Manager',
    subtitle: 'Scale Quality. Maintain Standards. Empower Teams.',
    benefits: [
      'Consistent frameworks across all team projects',
      'Quality benchmarks based on learning science',
      'Team collaboration and review workflows',
      'Usage analytics and productivity tracking (Enterprise)',
      'Onboarding acceleration for junior designers',
      'Predictable timelines and cost efficiency',
      'Subscription tiers that scale with your team',
    ],
    stats: [
      { value: 10, suffix: 'x', label: 'Faster Onboarding' },
      { value: 99, suffix: '%', label: 'Quality Consistency' },
    ],
    color: '#f59e0b',
    gradient: 'from-[#f59e0b] to-[#fbbf24]',
  },
  {
    id: 'ld-leader',
    icon: <TrendingUp className="h-5 w-5" strokeWidth={2} />,
    label: 'Leader',
    title: 'L&D Leader',
    subtitle: 'Strategic Learning Architecture at Enterprise Scale',
    benefits: [
      'Business alignment with organizational KPIs',
      'Scalable frameworks across departments',
      'Data-driven decision support and analytics',
      'Stakeholder communication tools (professional designs)',
      'Enterprise features: SSO, API access, custom reporting',
      'ROI tracking and cost reduction metrics',
      'Dedicated support and implementation assistance',
    ],
    stats: [
      { value: 61, suffix: '%', label: 'Cost Reduction' },
      { value: 6900, suffix: '$', label: 'Annual Savings' },
    ],
    color: '#8b5cf6',
    gradient: 'from-[#8b5cf6] to-[#a78bfa]',
  },
];
